// Auto-generated 100 Curated Offline Google Fonts Registry
import { FontCategory } from '../types/textOverlay';

export interface AppFont {
  id: string;
  name: string;
  family: string;
  category: FontCategory;
  asset: any;
}

export const FONT_CATEGORIES: { id: FontCategory; label: string; icon: string }[] = [
  { id: 'all', label: 'All', icon: 'apps' },
  { id: 'pixel', label: 'Pixel & 8-Bit', icon: 'game-controller' },
  { id: 'cinematic', label: 'Cinematic', icon: 'film' },
  { id: 'cursive', label: 'Cursive', icon: 'brush' },
  { id: 'comic', label: 'Comic', icon: 'chatbubble-ellipses' },
  { id: 'scifi', label: 'Sci-Fi', icon: 'planet' },
  { id: 'spooky', label: 'Spooky', icon: 'skull' },
  { id: 'modern', label: 'Modern', icon: 'sparkles' },
];

export const APP_FONTS: AppFont[] = [
  {
    id: 'PressStart2P',
    name: 'Press Start 2P',
    family: 'PressStart2P',
    category: 'pixel',
    asset: require('../../assets/fonts/PressStart2P-Regular.ttf'),
  },
  {
    id: 'VT323',
    name: 'VT323',
    family: 'VT323',
    category: 'pixel',
    asset: require('../../assets/fonts/VT323-Regular.ttf'),
  },
  {
    id: 'Silkscreen',
    name: 'Silkscreen',
    family: 'Silkscreen',
    category: 'pixel',
    asset: require('../../assets/fonts/Silkscreen-Regular.ttf'),
  },
  {
    id: 'DotGothic16',
    name: 'DotGothic16',
    family: 'DotGothic16',
    category: 'pixel',
    asset: require('../../assets/fonts/DotGothic16-Regular.ttf'),
  },
  {
    id: 'BlackOpsOne',
    name: 'Black Ops One',
    family: 'BlackOpsOne',
    category: 'pixel',
    asset: require('../../assets/fonts/BlackOpsOne-Regular.ttf'),
  },
  {
    id: 'RubikGlitch',
    name: 'Rubik Glitch',
    family: 'RubikGlitch',
    category: 'pixel',
    asset: require('../../assets/fonts/RubikGlitch-Regular.ttf'),
  },
  {
    id: 'ChakraPetch',
    name: 'Chakra Petch',
    family: 'ChakraPetch',
    category: 'pixel',
    asset: require('../../assets/fonts/ChakraPetch-Bold.ttf'),
  },
  {
    id: 'Quantico',
    name: 'Quantico',
    family: 'Quantico',
    category: 'pixel',
    asset: require('../../assets/fonts/Quantico-Bold.ttf'),
  },
  {
    id: 'AudiowidePixel',
    name: 'Audiowide',
    family: 'AudiowidePixel',
    category: 'pixel',
    asset: require('../../assets/fonts/Audiowide-Regular.ttf'),
  },
  {
    id: 'Wallpoet',
    name: 'Wallpoet',
    family: 'Wallpoet',
    category: 'pixel',
    asset: require('../../assets/fonts/Wallpoet-Regular.ttf'),
  },
  {
    id: 'Megrim',
    name: 'Megrim',
    family: 'Megrim',
    category: 'pixel',
    asset: require('../../assets/fonts/Megrim.ttf'),
  },
  {
    id: 'GeostarFill',
    name: 'Geostar Fill',
    family: 'GeostarFill',
    category: 'pixel',
    asset: require('../../assets/fonts/GeostarFill-Regular.ttf'),
  },
  {
    id: 'Cinzel',
    name: 'Cinzel',
    family: 'Cinzel',
    category: 'cinematic',
    asset: require('../../assets/fonts/Cinzel-Bold.ttf'),
  },
  {
    id: 'CinzelDecorative',
    name: 'Cinzel Decorative',
    family: 'CinzelDecorative',
    category: 'cinematic',
    asset: require('../../assets/fonts/CinzelDecorative-Bold.ttf'),
  },
  {
    id: 'BebasNeue',
    name: 'Bebas Neue',
    family: 'BebasNeue',
    category: 'cinematic',
    asset: require('../../assets/fonts/BebasNeue-Regular.ttf'),
  },
  {
    id: 'Anton',
    name: 'Anton',
    family: 'Anton',
    category: 'cinematic',
    asset: require('../../assets/fonts/Anton-Regular.ttf'),
  },
  {
    id: 'Oswald',
    name: 'Oswald',
    family: 'Oswald',
    category: 'cinematic',
    asset: require('../../assets/fonts/Oswald-Bold.ttf'),
  },
  {
    id: 'Montserrat',
    name: 'Montserrat',
    family: 'Montserrat',
    category: 'cinematic',
    asset: require('../../assets/fonts/Montserrat-Black.ttf'),
  },
  {
    id: 'PlayfairDisplay',
    name: 'Playfair Display',
    family: 'PlayfairDisplay',
    category: 'cinematic',
    asset: require('../../assets/fonts/PlayfairDisplay-Bold.ttf'),
  },
  {
    id: 'Prata',
    name: 'Prata',
    family: 'Prata',
    category: 'cinematic',
    asset: require('../../assets/fonts/Prata-Regular.ttf'),
  },
  {
    id: 'CastoroTitling',
    name: 'Castoro Titling',
    family: 'CastoroTitling',
    category: 'cinematic',
    asset: require('../../assets/fonts/CastoroTitling-Regular.ttf'),
  },
  {
    id: 'CormorantGaramond',
    name: 'Cormorant Garamond',
    family: 'CormorantGaramond',
    category: 'cinematic',
    asset: require('../../assets/fonts/CormorantGaramond-Bold.ttf'),
  },
  {
    id: 'AbrilFatface',
    name: 'Abril Fatface',
    family: 'AbrilFatface',
    category: 'cinematic',
    asset: require('../../assets/fonts/AbrilFatface-Regular.ttf'),
  },
  {
    id: 'Federo',
    name: 'Federo',
    family: 'Federo',
    category: 'cinematic',
    asset: require('../../assets/fonts/Federo-Regular.ttf'),
  },
  {
    id: 'Staatliches',
    name: 'Staatliches',
    family: 'Staatliches',
    category: 'cinematic',
    asset: require('../../assets/fonts/Staatliches-Regular.ttf'),
  },
  {
    id: 'YesevaOne',
    name: 'Yeseva One',
    family: 'YesevaOne',
    category: 'cinematic',
    asset: require('../../assets/fonts/YesevaOne-Regular.ttf'),
  },
  {
    id: 'Marcellus',
    name: 'Marcellus',
    family: 'Marcellus',
    category: 'cinematic',
    asset: require('../../assets/fonts/Marcellus-Regular.ttf'),
  },
  {
    id: 'UnifrakturMaguntia',
    name: 'Unifraktur',
    family: 'UnifrakturMaguntia',
    category: 'cinematic',
    asset: require('../../assets/fonts/UnifrakturMaguntia-Book.ttf'),
  },
  {
    id: 'Italiana',
    name: 'Italiana',
    family: 'Italiana',
    category: 'cinematic',
    asset: require('../../assets/fonts/Italiana-Regular.ttf'),
  },
  {
    id: 'Ultra',
    name: 'Ultra',
    family: 'Ultra',
    category: 'cinematic',
    asset: require('../../assets/fonts/Ultra-Regular.ttf'),
  },
  {
    id: 'GreatVibes',
    name: 'Great Vibes',
    family: 'GreatVibes',
    category: 'cursive',
    asset: require('../../assets/fonts/GreatVibes-Regular.ttf'),
  },
  {
    id: 'DancingScript',
    name: 'Dancing Script',
    family: 'DancingScript',
    category: 'cursive',
    asset: require('../../assets/fonts/DancingScript-Bold.ttf'),
  },
  {
    id: 'Pacifico',
    name: 'Pacifico',
    family: 'Pacifico',
    category: 'cursive',
    asset: require('../../assets/fonts/Pacifico-Regular.ttf'),
  },
  {
    id: 'Sacramento',
    name: 'Sacramento',
    family: 'Sacramento',
    category: 'cursive',
    asset: require('../../assets/fonts/Sacramento-Regular.ttf'),
  },
  {
    id: 'Satisfy',
    name: 'Satisfy',
    family: 'Satisfy',
    category: 'cursive',
    asset: require('../../assets/fonts/Satisfy-Regular.ttf'),
  },
  {
    id: 'Allura',
    name: 'Allura',
    family: 'Allura',
    category: 'cursive',
    asset: require('../../assets/fonts/Allura-Regular.ttf'),
  },
  {
    id: 'AlexBrush',
    name: 'Alex Brush',
    family: 'AlexBrush',
    category: 'cursive',
    asset: require('../../assets/fonts/AlexBrush-Regular.ttf'),
  },
  {
    id: 'Parisienne',
    name: 'Parisienne',
    family: 'Parisienne',
    category: 'cursive',
    asset: require('../../assets/fonts/Parisienne-Regular.ttf'),
  },
  {
    id: 'Caveat',
    name: 'Caveat',
    family: 'Caveat',
    category: 'cursive',
    asset: require('../../assets/fonts/Caveat-Bold.ttf'),
  },
  {
    id: 'Kalam',
    name: 'Kalam',
    family: 'Kalam',
    category: 'cursive',
    asset: require('../../assets/fonts/Kalam-Bold.ttf'),
  },
  {
    id: 'MarckScript',
    name: 'Marck Script',
    family: 'MarckScript',
    category: 'cursive',
    asset: require('../../assets/fonts/MarckScript-Regular.ttf'),
  },
  {
    id: 'Courgette',
    name: 'Courgette',
    family: 'Courgette',
    category: 'cursive',
    asset: require('../../assets/fonts/Courgette-Regular.ttf'),
  },
  {
    id: 'Yellowtail',
    name: 'Yellowtail',
    family: 'Yellowtail',
    category: 'cursive',
    asset: require('../../assets/fonts/Yellowtail-Regular.ttf'),
  },
  {
    id: 'HomemadeApple',
    name: 'Homemade Apple',
    family: 'HomemadeApple',
    category: 'cursive',
    asset: require('../../assets/fonts/HomemadeApple-Regular.ttf'),
  },
  {
    id: 'Damion',
    name: 'Damion',
    family: 'Damion',
    category: 'cursive',
    asset: require('../../assets/fonts/Damion-Regular.ttf'),
  },
  {
    id: 'KaushanScript',
    name: 'Kaushan Script',
    family: 'KaushanScript',
    category: 'cursive',
    asset: require('../../assets/fonts/KaushanScript-Regular.ttf'),
  },
  {
    id: 'PinyonScript',
    name: 'Pinyon Script',
    family: 'PinyonScript',
    category: 'cursive',
    asset: require('../../assets/fonts/PinyonScript-Regular.ttf'),
  },
  {
    id: 'Tangerine',
    name: 'Tangerine',
    family: 'Tangerine',
    category: 'cursive',
    asset: require('../../assets/fonts/Tangerine-Bold.ttf'),
  },
  {
    id: 'BadScript',
    name: 'Bad Script',
    family: 'BadScript',
    category: 'cursive',
    asset: require('../../assets/fonts/BadScript-Regular.ttf'),
  },
  {
    id: 'CedarvilleCursive',
    name: 'Cedarville Cursive',
    family: 'CedarvilleCursive',
    category: 'cursive',
    asset: require('../../assets/fonts/CedarvilleCursive-Regular.ttf'),
  },
  {
    id: 'Bangers',
    name: 'Bangers',
    family: 'Bangers',
    category: 'comic',
    asset: require('../../assets/fonts/Bangers-Regular.ttf'),
  },
  {
    id: 'LuckiestGuy',
    name: 'Luckiest Guy',
    family: 'LuckiestGuy',
    category: 'comic',
    asset: require('../../assets/fonts/LuckiestGuy-Regular.ttf'),
  },
  {
    id: 'Fredoka',
    name: 'Fredoka',
    family: 'Fredoka',
    category: 'comic',
    asset: require('../../assets/fonts/Fredoka-Bold.ttf'),
  },
  {
    id: 'Bungee',
    name: 'Bungee',
    family: 'Bungee',
    category: 'comic',
    asset: require('../../assets/fonts/Bungee-Regular.ttf'),
  },
  {
    id: 'BungeeShade',
    name: 'Bungee Shade',
    family: 'BungeeShade',
    category: 'comic',
    asset: require('../../assets/fonts/BungeeShade-Regular.ttf'),
  },
  {
    id: 'Chewy',
    name: 'Chewy',
    family: 'Chewy',
    category: 'comic',
    asset: require('../../assets/fonts/Chewy-Regular.ttf'),
  },
  {
    id: 'Righteous',
    name: 'Righteous',
    family: 'Righteous',
    category: 'comic',
    asset: require('../../assets/fonts/Righteous-Regular.ttf'),
  },
  {
    id: 'Sniglet',
    name: 'Sniglet',
    family: 'Sniglet',
    category: 'comic',
    asset: require('../../assets/fonts/Sniglet-ExtraBold.ttf'),
  },
  {
    id: 'CarterOne',
    name: 'Carter One',
    family: 'CarterOne',
    category: 'comic',
    asset: require('../../assets/fonts/CarterOne-Regular.ttf'),
  },
  {
    id: 'Chango',
    name: 'Chango',
    family: 'Chango',
    category: 'comic',
    asset: require('../../assets/fonts/Chango-Regular.ttf'),
  },
  {
    id: 'Boogaloo',
    name: 'Boogaloo',
    family: 'Boogaloo',
    category: 'comic',
    asset: require('../../assets/fonts/Boogaloo-Regular.ttf'),
  },
  {
    id: 'SpicyRice',
    name: 'Spicy Rice',
    family: 'SpicyRice',
    category: 'comic',
    asset: require('../../assets/fonts/SpicyRice-Regular.ttf'),
  },
  {
    id: 'TitanOne',
    name: 'Titan One',
    family: 'TitanOne',
    category: 'comic',
    asset: require('../../assets/fonts/TitanOne-Regular.ttf'),
  },
  {
    id: 'BowlbyOne',
    name: 'Bowlby One',
    family: 'BowlbyOne',
    category: 'comic',
    asset: require('../../assets/fonts/BowlbyOne-Regular.ttf'),
  },
  {
    id: 'Ribeye',
    name: 'Ribeye',
    family: 'Ribeye',
    category: 'comic',
    asset: require('../../assets/fonts/Ribeye-Regular.ttf'),
  },
  {
    id: 'Shrikhand',
    name: 'Shrikhand',
    family: 'Shrikhand',
    category: 'comic',
    asset: require('../../assets/fonts/Shrikhand-Regular.ttf'),
  },
  {
    id: 'Orbitron',
    name: 'Orbitron',
    family: 'Orbitron',
    category: 'scifi',
    asset: require('../../assets/fonts/Orbitron-Bold.ttf'),
  },
  {
    id: 'MajorMonoDisplay',
    name: 'Major Mono',
    family: 'MajorMonoDisplay',
    category: 'scifi',
    asset: require('../../assets/fonts/MajorMonoDisplay-Regular.ttf'),
  },
  {
    id: 'SpaceMono',
    name: 'Space Mono',
    family: 'SpaceMono',
    category: 'scifi',
    asset: require('../../assets/fonts/SpaceMono-Bold.ttf'),
  },
  {
    id: 'Michroma',
    name: 'Michroma',
    family: 'Michroma',
    category: 'scifi',
    asset: require('../../assets/fonts/Michroma-Regular.ttf'),
  },
  {
    id: 'Syncopate',
    name: 'Syncopate',
    family: 'Syncopate',
    category: 'scifi',
    asset: require('../../assets/fonts/Syncopate-Regular.ttf'),
  },
  {
    id: 'Electrolize',
    name: 'Electrolize',
    family: 'Electrolize',
    category: 'scifi',
    asset: require('../../assets/fonts/Electrolize-Regular.ttf'),
  },
  {
    id: 'BrunoAce',
    name: 'Bruno Ace',
    family: 'BrunoAce',
    category: 'scifi',
    asset: require('../../assets/fonts/BrunoAce-Regular.ttf'),
  },
  {
    id: 'RussoOne',
    name: 'Russo One',
    family: 'RussoOne',
    category: 'scifi',
    asset: require('../../assets/fonts/RussoOne-Regular.ttf'),
  },
  {
    id: 'Aldrich',
    name: 'Aldrich',
    family: 'Aldrich',
    category: 'scifi',
    asset: require('../../assets/fonts/Aldrich-Regular.ttf'),
  },
  {
    id: 'SairaStencilOne',
    name: 'Saira Stencil',
    family: 'SairaStencilOne',
    category: 'scifi',
    asset: require('../../assets/fonts/SairaStencilOne-Regular.ttf'),
  },
  {
    id: 'NovaMono',
    name: 'Nova Mono',
    family: 'NovaMono',
    category: 'scifi',
    asset: require('../../assets/fonts/NovaMono-Regular.ttf'),
  },
  {
    id: 'Chathura',
    name: 'Chathura',
    family: 'Chathura',
    category: 'scifi',
    asset: require('../../assets/fonts/Chathura-Bold.ttf'),
  },
  {
    id: 'Creepster',
    name: 'Creepster',
    family: 'Creepster',
    category: 'spooky',
    asset: require('../../assets/fonts/Creepster-Regular.ttf'),
  },
  {
    id: 'Nosifer',
    name: 'Nosifer',
    family: 'Nosifer',
    category: 'spooky',
    asset: require('../../assets/fonts/Nosifer-Regular.ttf'),
  },
  {
    id: 'Eater',
    name: 'Eater',
    family: 'Eater',
    category: 'spooky',
    asset: require('../../assets/fonts/Eater-Regular.ttf'),
  },
  {
    id: 'Frijole',
    name: 'Frijole',
    family: 'Frijole',
    category: 'spooky',
    asset: require('../../assets/fonts/Frijole-Regular.ttf'),
  },
  {
    id: 'Rye',
    name: 'Rye',
    family: 'Rye',
    category: 'spooky',
    asset: require('../../assets/fonts/Rye-Regular.ttf'),
  },
  {
    id: 'Monoton',
    name: 'Monoton',
    family: 'Monoton',
    category: 'spooky',
    asset: require('../../assets/fonts/Monoton-Regular.ttf'),
  },
  {
    id: 'Butcherman',
    name: 'Butcherman',
    family: 'Butcherman',
    category: 'spooky',
    asset: require('../../assets/fonts/Butcherman-Regular.ttf'),
  },
  {
    id: 'Shojumaru',
    name: 'Shojumaru',
    family: 'Shojumaru',
    category: 'spooky',
    asset: require('../../assets/fonts/Shojumaru-Regular.ttf'),
  },
  {
    id: 'Sancreek',
    name: 'Sancreek',
    family: 'Sancreek',
    category: 'spooky',
    asset: require('../../assets/fonts/Sancreek-Regular.ttf'),
  },
  {
    id: 'TradeWinds',
    name: 'Trade Winds',
    family: 'TradeWinds',
    category: 'spooky',
    asset: require('../../assets/fonts/TradeWinds-Regular.ttf'),
  },
  {
    id: 'MetalMania',
    name: 'Metal Mania',
    family: 'MetalMania',
    category: 'spooky',
    asset: require('../../assets/fonts/MetalMania-Regular.ttf'),
  },
  {
    id: 'Piedra',
    name: 'Piedra',
    family: 'Piedra',
    category: 'spooky',
    asset: require('../../assets/fonts/Piedra-Regular.ttf'),
  },
  {
    id: 'Poppins',
    name: 'Poppins',
    family: 'Poppins',
    category: 'modern',
    asset: require('../../assets/fonts/Poppins-Bold.ttf'),
  },
  {
    id: 'Inter',
    name: 'Inter',
    family: 'Inter',
    category: 'modern',
    asset: require('../../assets/fonts/Inter-Bold.ttf'),
  },
  {
    id: 'Raleway',
    name: 'Raleway',
    family: 'Raleway',
    category: 'modern',
    asset: require('../../assets/fonts/Raleway-Bold.ttf'),
  },
  {
    id: 'Outfit',
    name: 'Outfit',
    family: 'Outfit',
    category: 'modern',
    asset: require('../../assets/fonts/Outfit-Bold.ttf'),
  },
  {
    id: 'Comfortaa',
    name: 'Comfortaa',
    family: 'Comfortaa',
    category: 'modern',
    asset: require('../../assets/fonts/Comfortaa-Bold.ttf'),
  },
  {
    id: 'Quicksand',
    name: 'Quicksand',
    family: 'Quicksand',
    category: 'modern',
    asset: require('../../assets/fonts/Quicksand-Bold.ttf'),
  },
  {
    id: 'Syne',
    name: 'Syne',
    family: 'Syne',
    category: 'modern',
    asset: require('../../assets/fonts/Syne-ExtraBold.ttf'),
  },
  {
    id: 'Epilogue',
    name: 'Epilogue',
    family: 'Epilogue',
    category: 'modern',
    asset: require('../../assets/fonts/Epilogue-Bold.ttf'),
  },
  {
    id: 'JosefinSans',
    name: 'Josefin Sans',
    family: 'JosefinSans',
    category: 'modern',
    asset: require('../../assets/fonts/JosefinSans-Bold.ttf'),
  },
  {
    id: 'Lexend',
    name: 'Lexend',
    family: 'Lexend',
    category: 'modern',
    asset: require('../../assets/fonts/Lexend-Bold.ttf'),
  }
];

export const CORE_FONT_IDS = [
  'PressStart2P',
  'Cinzel',
  'BebasNeue',
  'GreatVibes',
  'Pacifico',
  'Bangers',
  'LuckiestGuy',
  'Orbitron',
  'Creepster',
  'Poppins',
];
